In [5]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [6]:
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from torch.utils.data import Dataset, DataLoader
from torch import nn

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.


In [9]:
os.listdir(path)

['data.csv']

In [10]:
df = pd.read_csv(path + "/data.csv")

In [12]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [15]:
df.shape

(569, 33)

In [16]:
df.drop(columns=["Unnamed: 32", "id"], inplace=True)

In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

In [20]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
90         14.62         24.02           94.57      662.7          0.08974   
20         13.08         15.71           85.63      520.0          0.10750   
477        13.90         16.62           88.97      599.4          0.06828   
269        10.71         20.39           69.50      344.9          0.10820   
494        13.16         20.54           84.06      538.7          0.07335   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
90            0.08606         0.03102              0.02957         0.1685   
20            0.12700         0.04568              0.03110         0.1967   
477           0.05319         0.02224              0.01339         0.1813   
269           0.12890         0.08448              0.02867         0.1668   
494           0.05275         0.01800              0.01256         0.1713   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
90                  0.05866  ...         16.11          29.11   
20                  0.06811  ...         14.50          20.49   
477                 0.05536  ...         15.14          21.80   
269                 0.06862  ...         11.69          25.21   
494                 0.05888  ...         14.50          28.46   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
90            102.90       803.7           0.11150             0.1766   
20             96.09       630.5           0.13120             0.2776   
477           101.20       718.9           0.09384             0.2006   
269            76.51       410.4           0.13350             0.2550   
494            95.29       648.3           0.11180             0.1646   

     concavity_worst  concave points_worst  symmetry_worst  \
90           0.09189               0.06946          0.2522   
20           0.18900               0.07283          0.3184   
477          0.13840               0.06222          0.2679   
269          0.25340               0.08600          0.2605   
494          0.07698               0.04195          0.2687   

     fractal_dimension_worst  
90                   0.07246  
20                   0.08183  
477                  0.07698  
269                  0.08701  
494                  0.07429  

[5 rows x 30 columns]

In [22]:
y_train

90     B
20     B
477    B
269    B
494    B
      ..
463    B
323    M
514    M
493    B
357    B
Name: diagnosis, Length: 455, dtype: object

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train

array([[ 0.13023267,  1.05974755,  0.09551767, ..., -0.69346705,
        -0.62523572, -0.6549398 ],
       [-0.31316995, -0.83026479, -0.27642355, ..., -0.64237339,
         0.46983022, -0.08799376],
       [-0.07707245, -0.62329593, -0.13746565, ..., -0.80323505,
        -0.36552975, -0.38145035],
       ...,
       [ 0.25403989, -0.06607208,  0.20743288, ..., -0.04850428,
        -1.02223848, -0.83161882],
       [-0.49168269, -1.48528712, -0.55933187, ..., -1.34024919,
        -1.02554683, -0.786844  ],
       [-0.08571016, -0.71654564, -0.15618752, ..., -0.90420947,
        -0.88990422, -0.73541346]])

#Label Encoder

In [27]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [30]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [31]:
y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0])

# Numpy to Pytorch tensor

In [35]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float64))
X_test_tensor = torch.from_numpy(X_test.astype(np.float64))
y_train_tensor = torch.from_numpy(y_train.astype(np.float64))
y_test_tensor = torch.from_numpy(y_test.astype(np.float64))

In [36]:
X_train_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]), torch.Size([114]))

# Defining Model

In [66]:
class MySimpleNN:
    def __init__(self, x):
        self.weights = torch.randn(x.shape[1], 1,
                                   dtype=torch.float64,
                                   requires_grad=True)
        self.bias = torch.zeros(1,
                                dtype=torch.float64,
                                requires_grad=True)

    def forward(self, x):
        z = torch.matmul(x, self.weights) + self.bias
        return torch.sigmoid(z)

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [67]:
# Important Parameters
learning_rate = 0.1
epochs= 25

# Training Pipline

In [68]:
#  create Model
model = MySimpleNN(X_train_tensor)

#defined in loops
# Forward Pass
for epoch in range(epochs):
  # backward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # pss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epochs: {epochs + 1}, Loss: {loss.item()}')


  #backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  # print losss in each epoch
  print(f'Epochs: {epoch + 1}, Loss: {loss.item()}')

Epochs: 1, Loss: 1.8603279379171476
Epochs: 2, Loss: 1.766755574458193
Epochs: 3, Loss: 1.6834693461267376
Epochs: 4, Loss: 1.6100549887524194
Epochs: 5, Loss: 1.5460567596808235
Epochs: 6, Loss: 1.4909923714291091
Epochs: 7, Loss: 1.443954179038164
Epochs: 8, Loss: 1.4034278647431557
Epochs: 9, Loss: 1.3691878209811426
Epochs: 10, Loss: 1.3399151966283296
Epochs: 11, Loss: 1.314415645735576
Epochs: 12, Loss: 1.291746929738449
Epochs: 13, Loss: 1.271220777093494
Epochs: 14, Loss: 1.2523501375512887
Epochs: 15, Loss: 1.2347926206222781
Epochs: 16, Loss: 1.2183060252025637
Epochs: 17, Loss: 1.2027167659846503
Epochs: 18, Loss: 1.1878982830236582
Epochs: 19, Loss: 1.1737564602716104
Epochs: 20, Loss: 1.1602197923245092
Epochs: 21, Loss: 1.147232727665052
Epochs: 22, Loss: 1.134751130703588
Epochs: 23, Loss: 1.1227391593145466
Epochs: 24, Loss: 1.111167092145157
Epochs: 25, Loss: 1.1000097975261856


In [69]:
model.weights

tensor([[ 0.5387],
        [ 0.5156],
        [-0.6599],
        [ 1.4155],
        [ 2.2281],
        [-1.6047],
        [-1.0082],
        [-0.4324],
        [-1.2237],
        [-0.7307],
        [ 0.8453],
        [-0.2393],
        [ 0.8004],
        [-1.3425],
        [ 0.0711],
        [-0.2252],
        [ 1.2274],
        [ 0.2014],
        [ 0.3192],
        [ 0.3686],
        [-0.0664],
        [ 0.6703],
        [-0.2199],
        [-0.6243],
        [ 0.6879],
        [ 0.1564],
        [-0.1840],
        [ 0.1766],
        [-0.3702],
        [ 0.5152]], dtype=torch.float64, requires_grad=True)

In [71]:
model.bias

tensor([-0.2542], dtype=torch.float64, requires_grad=True)

# Model Evaluation

In [72]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

print(y_pred)

tensor([[0.2383],
        [0.3721],
        [0.1729],
        [0.2709],
        [0.8878],
        [0.1017],
        [0.1952],
        [0.1874],
        [0.2643],
        [0.7530],
        [0.3539],
        [0.6412],
        [0.6853],
        [0.6370],
        [0.0583],
        [0.3672],
        [0.6608],
        [0.3614],
        [0.0681],
        [0.3995],
        [0.2318],
        [0.6263],
        [0.6853],
        [0.5573],
        [0.9522],
        [0.2191],
        [0.2183],
        [0.0811],
        [0.7582],
        [0.9028],
        [0.7326],
        [0.3374],
        [0.7763],
        [0.0076],
        [0.8992],
        [0.7647],
        [0.1609],
        [0.6643],
        [0.2689],
        [0.2593],
        [0.2103],
        [0.4329],
        [0.4347],
        [0.0176],
        [0.1412],
        [0.0060],
        [0.2042],
        [0.9285],
        [0.6242],
        [0.5093],
        [0.0026],
        [0.7743],
        [0.4815],
        [0.2114],
        [0.7793],
        [0