In [4]:
import torch
print(torch.__version__)

2.9.0+cu126


In [5]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
    print("Number of available GPUs:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. You can use GPU acceleration.
Number of available GPUs: Tesla T4


In [6]:
# Creating a tensor
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor A:")
print(tensor_a)

Tensor A:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
a = torch.empty(3, 4)

In [8]:
type(a)

torch.Tensor

In [9]:
# manual seed
torch.manual_seed(42)
torch.rand(4,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])

In [10]:
torch.manual_seed(42)
torch.rand(4, 4)                     #reproducible results

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])

In [11]:
# Other ways
print("Using arange: ", torch.arange(1, 10, 2))
print("Using linspace: ", torch.linspace(0, 1, steps=5))
print("Using ones: ", torch.ones(2, 3))
print("using eye: ", torch.eye(5))
print("Using FUll: ", torch.full((2, 3), 7))

Using arange:  tensor([1, 3, 5, 7, 9])
Using linspace:  tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
Using ones:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using FUll:  tensor([[7, 7, 7],
        [7, 7, 7]])


# Tensor Shape

In [12]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [13]:
x.shape

torch.Size([3])

In [14]:
torch.empty_like(x)

tensor([134698496826672, 134698496826672,              32])

In [15]:
torch.zeros_like(x)

tensor([0, 0, 0])

In [16]:
torch.ones_like(x)

tensor([1, 1, 1])

# Tensor data Type

In [17]:
x.dtype

torch.int64

In [18]:
# assign data type
y = torch.tensor([1, 2, 3], dtype=torch.float32)      #specifying data type
y.dtype

torch.float32

In [19]:
y = y.type(torch.int64)          #changing data type
y.dtype

torch.int64

# Mathematical Operations

In [20]:
# 1. Scaler Operation
x = torch.rand(2, 2)
x

tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])

In [21]:
x + 2, x-2,  x*2, x/3, (x*100)/3, x

(tensor([[2.8854, 2.5739],
         [2.2666, 2.6274]]),
 tensor([[-1.1146, -1.4261],
         [-1.7334, -1.3726]]),
 tensor([[1.7709, 1.1478],
         [0.5332, 1.2549]]),
 tensor([[0.2951, 0.1913],
         [0.0889, 0.2091]]),
 tensor([[29.5148, 19.1301],
         [ 8.8860, 20.9150]]),
 tensor([[0.8854, 0.5739],
         [0.2666, 0.6274]]))

In [22]:
# Element-wise operations
z = torch.rand(2, 2)

In [23]:
print(x + z)

tensor([[1.1551, 1.0153],
        [0.5635, 1.4591]])


In [24]:
x*z, x//z, x**z

(tensor([[0.2387, 0.2533],
         [0.0792, 0.5218]]),
 tensor([[3., 1.],
         [0., 0.]]),
 tensor([[0.9677, 0.7826],
         [0.6753, 0.6787]]))

In [25]:
# abs
torch.abs(y)

tensor([1, 2, 3])

In [26]:
torch.neg(y)

tensor([-1, -2, -3])

In [27]:
torch.round(y)

tensor([1, 2, 3])

In [28]:
torch.floor(x)

tensor([[0., 0.],
        [0., 0.]])

In [29]:
torch.clamp(x, min=2, max=3)

tensor([[2., 2.],
        [2., 2.]])

# Reduction operation

In [30]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[9, 3, 1],
        [9, 7, 9]])

In [31]:
# Sum
torch.sum(e) , torch.sum(e, dim=0), torch.sum(e,dim = 1 )

(tensor(38), tensor([18, 10, 10]), tensor([13, 25]))

In [32]:
# Mean 
e = e.type(torch.float16)
torch.mean(e), torch.median(e), torch.var_mean(e)

(tensor(6.3320, dtype=torch.float16),
 tensor(7., dtype=torch.float16),
 (tensor(12.2656, dtype=torch.float16), tensor(6.3320, dtype=torch.float16)))

In [33]:
# arg min and max
torch.argmax(e), torch.argmin(e)

(tensor(0), tensor(2))

# Matrix Operation

In [34]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

In [35]:
f, g

(tensor([[2, 0, 5],
         [9, 3, 4]]),
 tensor([[9, 6],
         [2, 0],
         [6, 2]]))

In [36]:
# Matrix Mulitiplication
torch.matmul(f, g)

tensor([[ 48,  22],
        [111,  62]])

In [37]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [38]:
torch.dot(vector1, vector2)

tensor(11)

In [39]:
torch.transpose(f, 0, 1)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

# 6. Special Function

In [40]:
k = torch.randint(size=(2, 3), low=0, high=10)
k

tensor([[7, 9, 7],
        [3, 3, 4]])

In [41]:
torch.log(k)

tensor([[1.9459, 2.1972, 1.9459],
        [1.0986, 1.0986, 1.3863]])

In [42]:
torch.exp(k)

tensor([[1096.6332, 8103.0840, 1096.6332],
        [  20.0855,   20.0855,   54.5981]])

In [43]:
torch.sqrt(k)

tensor([[2.6458, 3.0000, 2.6458],
        [1.7321, 1.7321, 2.0000]])

In [44]:
torch.sigmoid(k)

tensor([[0.9991, 0.9999, 0.9991],
        [0.9526, 0.9526, 0.9820]])

# Inplace Operations

In [45]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
m, n

(tensor([[0.7539, 0.1952, 0.0050],
         [0.3068, 0.1165, 0.9103]]),
 tensor([[0.6440, 0.7071, 0.6581],
         [0.4913, 0.8913, 0.1447]]))

In [46]:
m.add_(n)

tensor([[1.3979, 0.9024, 0.6632],
        [0.7981, 1.0078, 1.0550]])

In [47]:
torch.relu_(m)

tensor([[1.3979, 0.9024, 0.6632],
        [0.7981, 1.0078, 1.0550]])

In [48]:
m.relu_()

tensor([[1.3979, 0.9024, 0.6632],
        [0.7981, 1.0078, 1.0550]])

In [49]:
m

tensor([[1.3979, 0.9024, 0.6632],
        [0.7981, 1.0078, 1.0550]])

# Copy a Tensor

In [50]:
a = torch.rand(2, 3)
a

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [51]:
b = a
b

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [52]:
a[0][0] = 0
a

tensor([[0.0000, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [53]:
b #change in b without operation

tensor([[0.0000, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [54]:
id(b), id(a)

(134693901066448, 134693901066448)

In [55]:
# Use clone function


In [56]:
b = a.clone()

In [57]:
b

tensor([[0.0000, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [58]:
a[0][1] = 0

In [59]:
b

tensor([[0.0000, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

# Tensor Operations on GPU

In [60]:
torch.cuda.is_available()

True

In [61]:
device = torch.device('cuda')

In [62]:
torch.rand((2, 3), device= device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [63]:
a = torch.rand(2, 3)

In [64]:
a.to(device)

tensor([[0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]], device='cuda:0')

# Reshaping Tensors

In [66]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [67]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [68]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.9811, 0.0874, 0.0041, 0.1088],
         [0.1637, 0.7025, 0.6790, 0.9155],
         [0.2418, 0.1591, 0.7653, 0.2979]],

        [[0.8035, 0.3813, 0.7860, 0.1115],
         [0.2477, 0.6524, 0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374, 0.2331]]])

In [70]:
# Permute
b.permute(2,0,1)

tensor([[[0.9811, 0.1637, 0.2418],
         [0.8035, 0.2477, 0.7980]],

        [[0.0874, 0.7025, 0.1591],
         [0.3813, 0.6524, 0.8399]],

        [[0.0041, 0.6790, 0.7653],
         [0.7860, 0.6057, 0.1374]],

        [[0.1088, 0.9155, 0.2979],
         [0.1115, 0.3725, 0.2331]]])

In [71]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [75]:
# Unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [81]:
# squeeze
c.squeeze(2)

tensor([[[0.2082, 0.0980, 0.3070],
         [0.1486, 0.5924, 0.4587],
         [0.2875, 0.1980, 0.9834],
         ...,
         [0.0687, 0.2582, 0.6964],
         [0.2131, 0.4356, 0.8596],
         [0.6106, 0.3088, 0.6486]],

        [[0.1985, 0.8938, 0.9943],
         [0.7578, 0.2734, 0.6988],
         [0.3492, 0.4294, 0.5088],
         ...,
         [0.2123, 0.0331, 0.6644],
         [0.4455, 0.2274, 0.2382],
         [0.0948, 0.2789, 0.0934]],

        [[0.2093, 0.9348, 0.5809],
         [0.4613, 0.4232, 0.3528],
         [0.8494, 0.8597, 0.1182],
         ...,
         [0.8076, 0.1027, 0.4122],
         [0.6103, 0.1959, 0.0014],
         [0.3356, 0.5435, 0.3672]],

        ...,

        [[0.5800, 0.9021, 0.9839],
         [0.2456, 0.5330, 0.9863],
         [0.7777, 0.1989, 0.8833],
         ...,
         [0.9990, 0.5881, 0.1916],
         [0.6532, 0.1945, 0.4250],
         [0.4819, 0.4350, 0.7185]],

        [[0.4524, 0.0080, 0.5304],
         [0.2460, 0.3009, 0.1823],
         [0.

# Numpy

In [82]:
import numpy as np

In [84]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [86]:
b = a.numpy()
b

array([1, 2, 3])

In [87]:
type(b)

numpy.ndarray

In [89]:
c = torch.from_numpy(b)
type(c)

torch.Tensor